### ISSUE TITLE
waves-dex.service: Failed with result 'exit-code'.

### ISSUE THREAD

**Issue by vsradkevich** [wavesplatform/matcher#437]
Ubuntu 18.04

Installed waves_1.2.13_all.deb, waves-dex-extension_2.2.4_all.deb, waves-dex_2.2.4_all.deb

In this case, the port is open:

```
$ sudo netstat -tulpn | grep LISTEN
tcp6 0 0 127.0.0.1:6869 ::: * LISTEN 1679669 / java
tcp6 0 0 127.0.0.1:6887 ::: * LISTEN 1679669 / java
```

Blockchain loaded:

```
Jan 13 09:30:21 vps-0-sdtm5a.tilaa.cloud waves [1679669]: INFO c.w.s.BlockchainUpdaterImpl - MicroBlock (CeR4PNG ... -> 5YPrXxV ..., txs = 2) appended, diff = 10782cdb
Jan 13 09:30:23 vps-0-sdtm5a.tilaa.cloud waves [1679669]: INFO c.w.s.BlockchainUpdaterImpl - MicroBlock (FfVabRi ... -> CeR4PNG ..., txs = 2) appended, diff = 68f8605c
Jan 13 09:30:25 vps-0-sdtm5a.tilaa.cloud waves [1679669]: INFO c.w.s.BlockchainUpdaterImpl - MicroBlock (3niGw5w ... -> FfVabRi ..., txs = 2) appended, diff = 7bdce2f8

```
But waves-dex gives an error:

```
Jan 13 09:26:57 vps-0-sdtm5a.tilaa.cloud waves-dex [1783698]: 2021-01-13 08: 26: 57,412 INFO [main] cwdex.Application $ - DEX v2.2.4 Blockchain Id: W
Jan 13 09:26:57 vps-0-sdtm5a.tilaa.cloud waves-dex [1783698]: 2021-01-13 08: 26: 57,545 ERROR [main] c.w.d.a.RootActorSystem $ - Error while initializing actor system wavesplatform
Jan 13 09:26:57 vps-0-sdtm5a.tilaa.cloud waves-dex [1783698]: java.lang.RuntimeException: A file '/var/lib/waves-dex/account.dat' doesn't exist
Jan 13 09:26:57 vps-0-sdtm5a.tilaa.cloud waves-dex [1783698]: at com.wavesplatform.dex.domain.utils.package $ EitherExt2.explicitGet (package.scala: 30)
Jan 13 09:26:57 vps-0-sdtm5a.tilaa.cloud waves-dex [1783698]: at com.wavesplatform.dex.Application. <init> (Application.scala: 87)
Jan 13 09:26:57 vps-0-sdtm5a.tilaa.cloud waves-dex [1783698]: at com.wavesplatform.dex.Application $. $ Anonfun $ main $ 3 (Application.scala: 577)
Jan 13 09:26:57 vps-0-sdtm5a.tilaa.cloud waves-dex [1783698]: at com.wavesplatform.dex.Application $. $ Anonfun $ main $ 3 $ adapted (Application.scala: 559)
Jan 13 09:26:57 vps-0-sdtm5a.tilaa.cloud waves-dex [1783698]: at com.wavesplatform.dex.actors.RootActorSystem $ .start (RootActorSystem.scala: 26)
Jan 13 09:26:57 vps-0-sdtm5a.tilaa.cloud waves-dex [1783698]: at com.wavesplatform.dex.Application $ .main (Application.scala: 559)
Jan 13 09:26:57 vps-0-sdtm5a.tilaa.cloud waves-dex [1783698]: at com.wavesplatform.dex.Application.main (Application.scala)
Jan 13 09:26:57 vps-0-sdtm5a.tilaa.cloud systemd [1]: waves-dex.service: Main process exited, code = exited, status = 1 / FAILURE
Jan 13 09:26:57 vps-0-sdtm5a.tilaa.cloud systemd [1]: waves-dex.service: Failed with result 'exit-code'.
```

What is it connected with and how to fix it? I put it according to the instructions, in which, by the way, mistakes were made. Besides, you have a typo when installing java ("install deafult-jre").

**Comment by vsradkevich** [comment]
```
Jan 13 18:50:45 vps-0-sdtm5a.tilaa.cloud waves-dex[1868768]: Caused by: javax.crypto.BadPaddingException: Given final block not properly padded. Such issues can arise if a bad key is used during decryption.
Jan 13 18:50:45 vps-0-sdtm5a.tilaa.cloud waves-dex[1868768]:         at java.base/com.sun.crypto.provider.CipherCore.unpad(CipherCore.java:975)
Jan 13 18:50:45 vps-0-sdtm5a.tilaa.cloud waves-dex[1868768]:         at java.base/com.sun.crypto.provider.CipherCore.fillOutputBuffer(CipherCore.java:1056)
Jan 13 18:50:45 vps-0-sdtm5a.tilaa.cloud waves-dex[1868768]:         at java.base/com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:853)
Jan 13 18:50:45 vps-0-sdtm5a.tilaa.cloud waves-dex[1868768]:         at java.base/com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:446)
Jan 13 18:50:45 vps-0-sdtm5a.tilaa.cloud waves-dex[1868768]:         at java.base/javax.crypto.Cipher.doFinal(Cipher.java:2202)
Jan 13 18:50:45 vps-0-sdtm5a.tilaa.cloud waves-dex[1868768]:         at com.wavesplatform.dex.crypto.Enigma$.decrypt(Enigma.scala:51)
Jan 13 18:50:45 vps-0-sdtm5a.tilaa.cloud waves-dex[1868768]:         ... 7 common frames omitted
Jan 13 18:50:45 vps-0-sdtm5a.tilaa.cloud systemd[1]: waves-dex.service: Main process exited, code=exited, status=1/FAILURE
Jan 13 18:50:45 vps-0-sdtm5a.tilaa.cloud systemd[1]: waves-dex.service: Failed with result 'exit-code'.
```

**Comment by ngadiyak** [comment]
@vsradkevich did you [this step](https://github.com/wavesplatform/matcher#1-generating-account-storage)?

**Comment by vsradkevich** [comment]
> @vsradkevich did you [this step](https://github.com/wavesplatform/matcher#1-generating-account-storage)?

I didn’t do it at first, as the official documentation on the site doesn’t. But then after re-reading the github, I found this point, and made it (even repeated it several times) - and the result is my second message, in which the service writes to me that the password from my wallet does not work, although I set it very simple to check the functionality and rechecked several times, indicated in the config.

In general, you have a very incomprehensible instruction for everyone who is not a developer and does not understand what he is doing and why, despite my qualifications, it is very difficult to pass, one could lay out some more understandable example.

**Comment by cryptofunallday** [comment]
Most likely your error is directly related to the inconsistent instructions.  The odd referencing to previous closed issues or the "read 6-7" to every issue like this is not progressive in solving the obvious lack of proper/correct documentation.  I suggest everyone reading this to start making issue requests here to fix the documentation.  Maybe a flood of this request will inspire the owner to get it done instead of messing around everyone's time.
