### ISSUE TITLE
Error while initializing actor system wavesplatform

### ISSUE THREAD

**Issue by viraladmin** [wavesplatform/matcher#444]
Doing a clean install with no modifications of the lastest git clone from **waves** and from **matcher**. Both compile fine. Installing from zip the matcher. 

**_java -cp "/path/to/waves-all-1.2.17-2-g8041f98.jar:/path/to/lib/*" com.wavesplatform.Application /path/to/waves-custom-network.conf_**

    2021-01-22 01:40:22,409 INFO  [main] c.w.d.LevelDBFactory$ - Loaded com.wavesplatform.database.jna.LevelDBJNADBFactory with com.wavesplatform.database.jna.LevelDBJNADBFactory@7651218e
    2021-01-22 01:40:30,864 INFO  [main] c.w.crypto.package$ - Native provider used: true
    2021-01-22 01:40:30,898 INFO  [main] c.w.n.PeerDatabaseImpl - Loaded 0 known peer(s) from peers.dat
    2021-01-22 01:40:31,224 ERROR [main] c.w.actor.RootActorSystem$ - Error while initializing actor system wavesplatform java.lang.NoClassDefFoundError: scalapb/grpc/AbstractService
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at com.wavesplatform.Application.$anonfun$run$17(Application.scala:222)
        at scala.collection.immutable.List.map(List.scala:246)
        at scala.collection.immutable.List.map(List.scala:79)
        at com.wavesplatform.Application.run(Application.scala:221)
        at com.wavesplatform.Application$.$anonfun$startNode$4(Application.scala:564)
        at com.wavesplatform.Application$.$anonfun$startNode$4$adapted(Application.scala:561)
        at com.wavesplatform.actor.RootActorSystem$.start(RootActorSystem.scala:25)
        at com.wavesplatform.Application$.startNode(Application.scala:561)
        at com.wavesplatform.Application$.main(Application.scala:530)
        at com.wavesplatform.Application.main(Application.scala)
    Caused by: java.lang.ClassNotFoundException: scalapb.grpc.AbstractService
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 24 common frames omitted

conf file 

    waves {
      blockchain {
        type: MAINNET
      }
      extensions += "com.wavesplatform.dex.grpc.integration.DEXExtension"
      dex {
        # gRPC integration settings for Waves Node
        grpc.integration {
          host = "127.0.0.1" # "0.0.0.0" if the Matcher server connects to the Matcher extension from other machine
          port = 6888
        }
      }
      ....
    }
    
I have also tried with 

    extensions [
      "com.wavesplatform.dex.grpc.integration.DEXExtension"
    ]
    
I am on ubuntu 18.04 using java 1.8. I have also tried with 1.11 (openjdk) and java-15 (oracle)

**Comment by viraladmin** [comment]
I did not mean to add a label to this and don't know how to undo it.

**Comment by viraladmin** [comment]
THe answer to this seems to be not to use the master github branch. Which is mentioned on the front page but should be a HUGE bold. lol
