### ISSUE TITLE
matcher does not work, although I follow the instructions one to one.

### ISSUE THREAD

**Issue by windcoinplatform** [wavesplatform/matcher#98]
matcher does not work, although I follow the instructions one to one.
https://docs.wavesplatform.com/en/waves-node/extensions/matcher/matcher-install-ubuntu-deb.html

**Comment by vsuharnikov** [comment]
Try README.md from the project's main page: https://github.com/wavesplatform/dex#6-installing-and-running see 6 and 7

**Comment by dkabaka2027** [comment]
I tried instructions from project's main page on windows: [https://github.com/wavesplatform/dex#6-installing-and-running](https://github.com/wavesplatform/dex#6-installing-and-running); however, I get the following stack trace:
`
java.lang.ClassNotFoundException: com.wavesplatform.dex.grpc.integration.DEXExtension
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:332)
        at com.wavesplatform.Application.$anonfun$run$15(Application.scala:250)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
        at scala.collection.Iterator.foreach(Iterator.scala:941)
        at scala.collection.Iterator.foreach$(Iterator.scala:941)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
        at scala.collection.IterableLike.foreach(IterableLike.scala:74)
        at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
        at scala.collection.TraversableLike.map(TraversableLike.scala:238)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
        at scala.collection.AbstractTraversable.map(Traversable.scala:108)
        at com.wavesplatform.Application.run(Application.scala:249)
        at com.wavesplatform.Application$.$anonfun$startNode$4(Application.scala:500)
        at com.wavesplatform.Application$.$anonfun$startNode$4$adapted(Application.scala:480)
        at com.wavesplatform.actor.RootActorSystem$.start(RootActorSystem.scala:25)
        at com.wavesplatform.Application$.startNode(Application.scala:480)
        at com.wavesplatform.Application$.main(Application.scala:463)
        at com.wavesplatform.Application.main(Application.scala)
`
Clearly the class `com.wavesplatform.dex.grpc.integration.DEXExtension` cannot be found and it's evident when you extract the dex jar one cannot find it when searched.

The same happens when you try with the extension `com.wavesplatform.dex.Matcher` but this time it actually finds the extension and tries to invoke it's constructor but there's a mismatch of types as it takes `MatcherSettings` as compared to `ExtensionContext` like DexExtension does when you view the source; and in this case the following stack trace is evident:
`java.lang.reflect.InvocationTargetException: null
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
        at com.wavesplatform.Application.$anonfun$run$15(Application.scala:253)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
        at scala.collection.Iterator.foreach(Iterator.scala:941)
        at scala.collection.Iterator.foreach$(Iterator.scala:941)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
        at scala.collection.IterableLike.foreach(IterableLike.scala:74)
        at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
        at scala.collection.TraversableLike.map(TraversableLike.scala:238)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
        at scala.collection.AbstractTraversable.map(Traversable.scala:108)
        at com.wavesplatform.Application.run(Application.scala:249)
        at com.wavesplatform.Application$.$anonfun$startNode$4(Application.scala:500)
        at com.wavesplatform.Application$.$anonfun$startNode$4$adapted(Application.scala:480)
        at com.wavesplatform.actor.RootActorSystem$.start(RootActorSystem.scala:25)
        at com.wavesplatform.Application$.startNode(Application.scala:480)
        at com.wavesplatform.Application$.main(Application.scala:463)
        at com.wavesplatform.Application.main(Application.scala)
Caused by: java.lang.RuntimeException: InvalidAddress(Wrong addressBytes length: expected: 26, actual: 0)
        at com.wavesplatform.common.utils.package$EitherExt2.explicitGet(package.scala:20)
        at com.wavesplatform.dex.Matcher.<init>(Matcher.scala:48)
        ... 23 common frames omitted`

Any idea, considering refactoring the source to enable it to compile with project fetched from repository in `build.sbt`?

**Comment by vsuharnikov** [comment]
Probably you are trying to install a DEX of one version but doing that by instructions for other.  https://github.com/wavesplatform/dex#6-installing-and-running is actual for the `master` branch, for a specific version see `https://github.com/wavesplatform/dex/tree/{version}`, e.g. https://github.com/wavesplatform/dex/tree/v1.1.1

Could you show the full command you use to run the DEX?

We plan to ship a Docker container, but not in near future :(

**Comment by dkabaka2027** [comment]
Full Command:
`java -cp "D:\work\delala\server\jars\waves-all-1.1.7.jar;D:\work\delala\server\jars\lib\*" com.wavesplatform.Application .\waves.conf`

Waves Configuration:
`
waves {
  extensions = [
    "com.wavesplatform.dex.Matcher",
    "com.wavesplatform.dex.grpc.integration.DEXExtension",
    "com.wavesplatform.api.grpc.GRPCServerExtension"
  ]

  dex {
    # Matcher's account address
    # account = ""

    # Matcher REST API bind address
    bind-address = "127.0.0.1"

    # Matcher REST API port
    port = 6886

    grpc {
      host = "127.0.0.1" # "0.0.0.0" if the DEX server connects to the DEX extension from other machine 
      port = 6887

      integration {
  	    host = "127.0.0.1" # "0.0.0.0" if the DEX server connects to the DEX extension from other machine 
  	    port = 6887
  	  }
    }
  }
}
`

**Comment by dkabaka2027** [comment]
Tried 1.2.2 and DexExtension doesn't get enabled. No matcher API route and the log on STDOUT doesn't state 'Enabling DexExtension'? Sample initial log below:

2020-02-12 18:19:33,706 INFO  [main] c.w.Application$ - Starting...
2020-02-12 18:19:42,231 INFO  [ctor.default-dispatcher-3] a.event.slf4j.Slf4jLogger - Slf4jLogger started
2020-02-12 18:19:45,435 INFO  [main] c.w.Application$ - Waves v1.2.2 Blockchain Id: T
Enter password for your wallet
Password >
2020-02-12 18:20:28,861 INFO  [main] com.wavesplatform.package$ - Genesis block BlockHeader(1,1460678400000,67rpwLCuS5DGA8KGZXKsVQ7dnPb9goRLoKfgGbLfQg9WoLUgNY77E2jT11fem3coV9nAkguBACzrU1iyZM4B8roQ,153722867,11111111111111111111111111111111,2eEUvypDSivnzPiLrbYEW39SM8yMZ1aq4eJuiKfs4sEY,List(),-1,) has been added to the state
2020-02-12 18:20:39,304 INFO  [nio-worker-group-3-4] c.w.n.HandshakeHandler$Client - [c059790a 52.77.111.219:6863] Accepted handshake Handshake(wavesT,(1,1,8),TESTNET-3,1201993,Some(/52.77.111.219:6863))
2020-02-12 18:20:39,304 INFO  [nio-worker-group-3-2] c.w.n.HandshakeHandler$Client - [2a551445 52.28.66.217:6863] Accepted handshake Handshake(wavesT,(1,1,8),TESTNET-2,1348908,Some(/52.28.66.217:6863))
2020-02-12 18:20:40,091 INFO  [nio-worker-group-3-6] c.w.n.HandshakeHandler$Client - [fcfa22ee 52.51.92.182:6863] Accepted handshake Handshake(wavesT,(1,1,8),TESTNET-4,1181974,Some(/52.51.92.182:6863))
2020-02-12 18:20:40,389 INFO  [nio-worker-group-3-8] c.w.n.HandshakeHandler$Client - [fd5a9f72 52.30.47.67:6863] Accepted handshake Handshake(wavesT,(1,1,8),TESTNET-1,485741,Some(/52.30.47.67:6863))
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.protobuf.UnsafeUtil (file:/D:/work/delala/server/jars/waves-all-1.2.2.jar) to field java.nio.Buffer.address
WARNING: Please consider reporting this to the maintainers of com.google.protobuf.UnsafeUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2020-02-12 18:20:45,521 INFO  [nio-worker-group-3-10] c.w.n.HandshakeHandler$Client - [32005034 18.197.214.35:6863] Accepted handshake Handshake(wavesT,(1,1,7),TESTNET-27,592847,Some(/18.197.214.35:6863))
2020-02-12 18:20:47,269 INFO  [appender-49] c.w.s.BlockchainUpdaterImpl - New height: 100
2020-02-12 18:20:49,645 INFO  [appender-49] c.w.s.BlockchainUpdaterImpl - New height: 200
2020-02-12 18:20:50,483 INFO  [appender-49] c.w.s.BlockchainUpdaterImpl - New height: 300
2020-02-12 18:20:56,800 INFO  [appender-49] c.w.s.BlockchainUpdaterImpl - New height: 400
2020-02-12 18:20:58,752 INFO  [appender-49] c.w.s.BlockchainUpdaterImpl - New height: 500
2020-02-12 18:20:59,028 INFO  [appender-49] c.w.s.BlockchainUpdaterImpl - New height: 600
2020-02-12 18:21:02,189 INFO  [main] c.w.Application - REST API was bound on 127.0.0.1:6869

**Comment by cryptofunallday** [comment]
Is there some secret reason this user is having the same issue as others since 2019 considering it is now Feb 2021?  Where is the proper documentation to making this work without being disregarded or pointed to multiple previous issues that also lead to a non-working solution and waste of time?
